tests/inputs/54-some-numpy-ufuncs.py:10:4: E011 AttributeError: 'module' object has no attribute 'dtype'
